config/routes.rb
Happs::Application.routes.draw do
 
  root 'static_pages#landing'

  match "/landing",   to: "static_pages#landing", via: 'get'
  match "/about",     to: "static_pages#about",   via: 'get'

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,	presence: true, length: { maximum: 20 }
  validates :last_name,		presence: true, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

		def sign_up_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, 
				:password_confirmation)
		end

		def account_update_params
	    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
	  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update]

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	private

		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password,
				:password_confirmation)
		end

		def signed_in_user
			redirect_to new_user_session_url, 
				notice: "Please sign in." unless user_signed_in?
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Happs"
		page_title.empty? ? base_title : "#{base_title} | #{page_title}"
	end

end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options={size: 50})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: "#{@user.first_name} #{@user.last_name}", 
			class: "gravatar")
	end
	
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Happs", root_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><%= link_to "About", about_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li><%= link_to "Sign out", destroy_user_session_path, :method => "delete" %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Sign up", new_user_registration_path %></li>
					<li><%= link_to "Sign in", new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<%= render 'layouts/header' %>

<div class="container-fluid">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>Need to put in some info. ETA next 24hrs from whenever you're reading this.</p>

app/views/static_pages/landing.html.erb
<% provide(:title, "Welcome") %>
<h1>Welcome!</h1>
<p>This is the landing page of Happs. It's a static page, but it will soon have a sign-up form. :)</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h2>Edit <%= @user.first_name %></h2>
<h3>Update your profile</h3>

<%= form_for(@user, url: registration_path(resource_name), html: { method: :patch }) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :first_name %><br />
  <%= f.text_field :first_name, autofocus: true %></div>

  <div><%= f.label :last_name %><br />
  <%= f.text_field :last_name %></div>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %></div>

  <div><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

  <div><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %></div>

  <div><%= f.submit "Save changes" %></div>
<% end %>

<%= gravatar_for @user %>
<a href="http://gravatar.com/emails">change photo</a>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/users/show.html.erb
<% provide(:title, "#{@user.first_name} #{@user.last_name}") %>
First Name: <%= @user.first_name %>
Last Name: <%= @user.last_name %>
Email: <%= @user.email %>

<%= gravatar_for @user %>